aws_default:
  conn_type: aws
  extra:
    aws_access_key_id: '${AWS_ACCESS_KEY_ID}'
    aws_secret_access_key: '${AWS_SECRET_ACCESS_KEY}'
    region_name: '${AWS_DEFAULT_REGION}'

postgres_default:
  conn_type: postgres
  host: '${POSTGRES_HOST}'
  schema: '${POSTGRES_DB}'
  login: '${POSTGRES_USER}'
  password: '${POSTGRES_PASSWORD}'
  port: '${POSTGRES_PORT}' 